# Generated by Django 6.0.6 on 2026-07-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ British Pound'), ('NGN', '₦ Nigerian Naira')], default='USD', max_length=3),
        ),
    ]
