# Generated by Django 6.0.6 on 2026-08-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_category_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ British Pound'), ('NGN', '₦ Nigerian Naira')], default='NGN', max_length=3),
        ),
    ]
